title: Frish2021の小站
description: 神人网站
favicon: favicon.jpg
category_dir: category
url: https://www.coderfrish.me/

syntax_highlighter: prismjs

tag_generator:
  per_page: 9
  order_by: -date

category_generator:
  per_page: 5
  order_by: -date

index_generator:
  path: ''
  per_page: 5
  order_by: -date

markdown:
  plugins:
    - name: '@renbaoshuo/markdown-it-katex'

theme: hydrogen
