# 网站标题设置
subtitle:

author:
  website: https://www.coderfrish.me/
  name: Frish2021
  avatar: avatar.jpg
  description: 来自大狗嚼星球的高级生物
  email: 1573880184@qq.com

widget:
  recent:
    enabled: true
  tags:
    enabled: true

theme:
  enabled: true

search:
  enabled: true

commits:
  repo:
    name: CoderFrish/coderfrish-hexo-blog
    id: R_kgDOP6vGFA
  category:
    name: General
    id: DIC_kwDOP6vGFM4DBxSu
