# 网站标题设置
subtitle:

author:
  avatar: avatar.jpg
  email: 1573880184@qq.com

search:
  enabled: true

commits:
  enabled: true
  page:
    about: true
    post: true
  repo:
    name: CoderFrish/coderfrish-hexo-blog
    id: R_kgDOP6vGFA
  category:
    name: General
    id: DIC_kwDOP6vGFM4DBxSu
